[workspace]
channels = ["https://prefix.dev/glatzel", "conda-forge"]
name = "fornax"
platforms = ["win-64", "linux-64", "linux-aarch64", "osx-arm64"]

[dependencies]
libraw = "==0.22.0"
maturin = "==1.12.0"
pip = "==26.0.1"
python = "3.13.*"

imageio = "==2.37.0"
lazy-loader = "==0.4"
msgspec = "==0.20.0"
nomkl = "==1.0"
numpy = "2.3.*"
numpydoc = "==1.10.0"
pydantic = "==2.12.5"

# test
pytest = "==9.0.2"
pytest-cov = "==7.0.0"
