[workspace]
authors = ["Glatzel <893016099@qq.com>"]
channels = ["conda-forge", "https://prefix.dev/glatzel"]
name = "fornax"
platforms = ["win-64", "linux-64", "osx-arm64"]
version = "0.1.0"

[dependencies]
libraw = { version = "==0.21.5", channel = "https://prefix.dev/glatzel" }
maturin = "==1.11.5"
pip = "==25.3"
pkg-config = "==0.29.2"
python = "3.13.*"

imageio = "==2.37.0"
lazy-loader = "==0.4"
msgspec = "==0.20.0"
nomkl = "==1.0"
numpy = "2.3.*"
numpydoc = "==1.10.0"
pydantic = "==2.12.5"

# test
pytest = "==9.0.2"
pytest-cov = "==7.0.0"
